os: linux
dist: xenial
language: php

php:
  - 7.3
  - 7.4
  - 8.0
  - 8.1

branches:
  only:
    - master
    - /^v?\d+\.\d+\.\d+$/

install:
  - composer install --prefer-dist

script:
  - make test
  - make analyse

cache:
  directories:
    - $HOME/.composer/cache/files
    - vendor
